spring:
  config:
    activate:
      on-profile: dev

management:
  endpoint:
    health:
      show-details: always

app:
  integrations:
    cadastro:
      base-url: ${CADASTRO_BASE_URL:http://localhost:5001}

logging:
  level:
    org.springframework.security: INFO
