// <auto-generated />
using System;
using Identificacao.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identificacao.Infra.Migrations
{
    [DbContext(typeof(IdentificacaoDbContext))]
    [Migration("20260616004612_RenameMinioKeyToStorageFileId")]
    partial class RenameMinioKeyToStorageFileId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identificacao")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identificacao.Domain.Entities.Captacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalistaResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<string>("AnalistaResponsavelNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DistribuicaoProcessada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DistribuicaoProcessadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JustificativaCancelamento")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("Periodo")
                        .HasColumnType("date");

                    b.Property<Guid>("RubricaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioDeMusica")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RubricaId", "Periodo")
                        .IsUnique()
                        .HasDatabaseName("uq_captacoes_rubrica_periodo_ativa")
                        .HasFilter("\"Status\" != 'Cancelada'");

                    b.ToTable("Captacoes", "identificacao");
                });

            modelBuilder.Entity("Identificacao.Domain.Entities.ErroUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Coluna")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Linha")
                        .HasColumnType("integer");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UploadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UploadId")
                        .HasDatabaseName("ix_erros_upload");

                    b.ToTable("ErrosUpload", "identificacao");
                });

            modelBuilder.Entity("Identificacao.Domain.Entities.Execucao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CaptacaoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuracaoSegundos")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Fim")
                        .HasColumnType("time");

                    b.Property<Guid?>("FonogramaId")
                        .HasColumnType("uuid");

                    b.Property<string>("FonogramaIsrc")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<TimeOnly>("Inicio")
                        .HasColumnType("time");

                    b.Property<string>("Interpretes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObraIswc")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ObraTitulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TipoUtilizacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TituloPrograma")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CaptacaoId")
                        .HasDatabaseName("ix_execucoes_captacao");

                    b.HasIndex("ObraId")
                        .HasDatabaseName("ix_execucoes_obra");

                    b.HasIndex("TipoUtilizacaoId");

                    b.ToTable("Execucoes", "identificacao");
                });

            modelBuilder.Entity("Identificacao.Domain.Entities.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt", "Attempts")
                        .HasDatabaseName("ix_outbox_pendentes")
                        .HasFilter("\"PublishedAt\" IS NULL AND \"Attempts\" < 10");

                    b.ToTable("outbox_events", "identificacao");
                });

            modelBuilder.Entity("Identificacao.Domain.Entities.Rubrica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ExigeClassificacao")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("Rubricas", "identificacao");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1a2c3d4-0001-0000-0000-000000000001"),
                            ExigeClassificacao = false,
                            Nome = "Rádio AM/FM",
                            Sigla = "RADIO"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-0001-0000-0000-000000000002"),
                            ExigeClassificacao = true,
                            Nome = "TV Aberta",
                            Sigla = "TV_ABERTA"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-0001-0000-0000-000000000003"),
                            ExigeClassificacao = true,
                            Nome = "TV Fechada",
                            Sigla = "TV_FECHADA"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-0001-0000-0000-000000000004"),
                            ExigeClassificacao = true,
                            Nome = "Cinema",
                            Sigla = "CINEMA"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-0001-0000-0000-000000000005"),
                            ExigeClassificacao = true,
                            Nome = "Streaming Vídeo (VOD)",
                            Sigla = "VOD"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-0001-0000-0000-000000000006"),
                            ExigeClassificacao = false,
                            Nome = "Streaming Áudio",
                            Sigla = "STREAMING_AUDIO"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-0001-0000-0000-000000000007"),
                            ExigeClassificacao = false,
                            Nome = "Show",
                            Sigla = "SHOW"
                        });
                });

            modelBuilder.Entity("Identificacao.Domain.Entities.TipoUtilizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("TiposUtilizacao", "identificacao");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1e2f3a4-0001-0000-0000-000000000001"),
                            Descricao = "Tema de Abertura",
                            Peso = 1.0m,
                            Sigla = "TA"
                        },
                        new
                        {
                            Id = new Guid("d1e2f3a4-0001-0000-0000-000000000002"),
                            Descricao = "Tema de Encerramento",
                            Peso = 1.0m,
                            Sigla = "TE"
                        },
                        new
                        {
                            Id = new Guid("d1e2f3a4-0001-0000-0000-000000000003"),
                            Descricao = "Performance Cênica",
                            Peso = 1.0m,
                            Sigla = "PE"
                        },
                        new
                        {
                            Id = new Guid("d1e2f3a4-0001-0000-0000-000000000004"),
                            Descricao = "Background (Música de Fundo)",
                            Peso = 0.0833m,
                            Sigla = "BK"
                        });
                });

            modelBuilder.Entity("Identificacao.Domain.Entities.Upload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalistaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaptacaoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExecucoesCriadas")
                        .HasColumnType("integer");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("text");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StorageFileId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("TotalErros")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalLinhas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaptacaoId")
                        .HasDatabaseName("ix_uploads_captacao");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_uploads_status_processando")
                        .HasFilter("\"Status\" = 'Processando'");

                    b.ToTable("Uploads", "identificacao");
                });

            modelBuilder.Entity("Identificacao.Infra.Audit.AuditOutboxEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("AggregateId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("aggregate_type");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LockOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lock_owner");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_audit_outbox");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("uk_audit_outbox_event");

                    b.HasIndex("EventType", "CreatedAtUtc")
                        .HasDatabaseName("ix_audit_outbox_event_type");

                    b.HasIndex("Status", "AvailableAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_audit_outbox_pending");

                    b.ToTable("audit_outbox", "identificacao");
                });

            modelBuilder.Entity("Identificacao.Domain.Entities.Captacao", b =>
                {
                    b.HasOne("Identificacao.Domain.Entities.Rubrica", "Rubrica")
                        .WithMany()
                        .HasForeignKey("RubricaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rubrica");
                });

            modelBuilder.Entity("Identificacao.Domain.Entities.ErroUpload", b =>
                {
                    b.HasOne("Identificacao.Domain.Entities.Upload", "Upload")
                        .WithMany()
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("Identificacao.Domain.Entities.Execucao", b =>
                {
                    b.HasOne("Identificacao.Domain.Entities.Captacao", "Captacao")
                        .WithMany()
                        .HasForeignKey("CaptacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identificacao.Domain.Entities.TipoUtilizacao", "TipoUtilizacao")
                        .WithMany()
                        .HasForeignKey("TipoUtilizacaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Captacao");

                    b.Navigation("TipoUtilizacao");
                });

            modelBuilder.Entity("Identificacao.Domain.Entities.Upload", b =>
                {
                    b.HasOne("Identificacao.Domain.Entities.Captacao", "Captacao")
                        .WithMany()
                        .HasForeignKey("CaptacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Captacao");
                });
#pragma warning restore 612, 618
        }
    }
}
