// <auto-generated />
using System;
using Identificacao.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identificacao.Infra.Migrations
{
    [DbContext(typeof(IdentificacaoDbContext))]
    partial class IdentificacaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identificacao")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identificacao.Domain.Entities.Captacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalistaResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<string>("AnalistaResponsavelNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Periodo")
                        .HasColumnType("date");

                    b.Property<Guid>("RubricaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioDeMusica")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RubricaId", "Periodo")
                        .IsUnique()
                        .HasDatabaseName("uq_captacoes_rubrica_periodo_ativa")
                        .HasFilter("\"Status\" != 'Cancelada'");

                    b.ToTable("Captacoes", "identificacao");
                });

            modelBuilder.Entity("Identificacao.Domain.Entities.Rubrica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ExigeClassificacao")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("Rubricas", "identificacao");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1a2c3d4-0001-0000-0000-000000000001"),
                            ExigeClassificacao = false,
                            Nome = "Rádio AM/FM",
                            Sigla = "RADIO"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-0001-0000-0000-000000000002"),
                            ExigeClassificacao = true,
                            Nome = "TV Aberta",
                            Sigla = "TV_ABERTA"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-0001-0000-0000-000000000003"),
                            ExigeClassificacao = true,
                            Nome = "TV Fechada",
                            Sigla = "TV_FECHADA"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-0001-0000-0000-000000000004"),
                            ExigeClassificacao = true,
                            Nome = "Cinema",
                            Sigla = "CINEMA"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-0001-0000-0000-000000000005"),
                            ExigeClassificacao = true,
                            Nome = "Streaming Vídeo (VOD)",
                            Sigla = "VOD"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-0001-0000-0000-000000000006"),
                            ExigeClassificacao = false,
                            Nome = "Streaming Áudio",
                            Sigla = "STREAMING_AUDIO"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-0001-0000-0000-000000000007"),
                            ExigeClassificacao = false,
                            Nome = "Show",
                            Sigla = "SHOW"
                        });
                });

            modelBuilder.Entity("Identificacao.Domain.Entities.Captacao", b =>
                {
                    b.HasOne("Identificacao.Domain.Entities.Rubrica", "Rubrica")
                        .WithMany()
                        .HasForeignKey("RubricaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rubrica");
                });
#pragma warning restore 612, 618
        }
    }
}
