services:
  # Como agora usamos a REST API pública do MusicBrainz, não precisamos mais subir o PostgreSQL!
  # O contêiner abaixo serve apenas para te dar um ambiente Node.js isolado na mesma rede da sua API.
  importer:
    image: node:20-alpine
    container_name: mcad-mb-importer
    working_dir: /app
    volumes:
      - ./:/app
    command: tail -f /dev/null
    environment:
      - CADASTRO_API_URL=https://mcad-cadastro.tasso.dev.br/api/v1
      - JWT_TOKEN=