// <auto-generated />
using System;
using Cadastro.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cadastro.Infra.Data.Migrations
{
    [DbContext(typeof(CadastroDbContext))]
    [Migration("20260403182402_SyncModel")]
    partial class SyncModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cadastro")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cadastro.Domain.Entities.Associacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character(18)")
                        .IsFixedLength();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("uq_associacoes_cnpj");

                    b.HasIndex("Sigla")
                        .IsUnique()
                        .HasDatabaseName("uq_associacoes_sigla");

                    b.ToTable("associacoes", "cadastro");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Cnpj = "50.997.063/0001-32",
                            Nome = "Associação Brasileira de Música e Artes",
                            Sigla = "ABRAMUS"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            Cnpj = "30.713.325/0001-82",
                            Nome = "Associação de Músicos, Arranjadores e Regentes",
                            Sigla = "AMAR"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            Cnpj = "43.985.563/0001-99",
                            Nome = "Associação de Intérpretes e Músicos",
                            Sigla = "ASSIM"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            Cnpj = "33.780.222/0001-23",
                            Nome = "Sociedade Brasileira de Autores, Compositores e Escritores de Música",
                            Sigla = "SBACEM"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-efab-345678901234"),
                            Cnpj = "62.092.010/0001-51",
                            Nome = "Sociedade Independente de Compositores e Autores Musicais",
                            Sigla = "SICAM"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            Cnpj = "33.748.146/0001-79",
                            Nome = "Sociedade Brasileira de Administração e Proteção de Direitos Intelectuais",
                            Sigla = "SOCINPRO"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-3456-abcd-567890123456"),
                            Cnpj = "33.576.166/0001-00",
                            Nome = "União Brasileira de Compositores",
                            Sigla = "UBC"
                        });
                });

            modelBuilder.Entity("Cadastro.Domain.Entities.Fonograma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BloqueioJustificativa")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataGravacao")
                        .HasColumnType("DATE");

                    b.Property<DateOnly?>("DataLancamento")
                        .HasColumnType("DATE");

                    b.Property<Guid?>("FonogramaDepuradoParaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Isrc")
                        .IsRequired()
                        .HasColumnType("VARCHAR(12)");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaisOrigem")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<bool>("PercentuaisDesatualizados")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.Property<string>("UrlAudio")
                        .HasColumnType("VARCHAR(500)");

                    b.HasKey("Id");

                    b.HasIndex("FonogramaDepuradoParaId")
                        .HasDatabaseName("ix_fonogramas_depurado_para")
                        .HasFilter("\"FonogramaDepuradoParaId\" IS NOT NULL");

                    b.HasIndex("Isrc")
                        .IsUnique()
                        .HasDatabaseName("uq_fonogramas_isrc")
                        .HasFilter("\"Isrc\" IS NOT NULL");

                    b.HasIndex("ObraId")
                        .HasDatabaseName("ix_fonogramas_obra");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_fonogramas_status");

                    b.ToTable("fonogramas", "cadastro", t =>
                        {
                            t.HasCheckConstraint("ck_fonogramas_status", "\"Status\" IN ('PENDENTE_VALIDACAO', 'PENDENTE_DOCUMENTACAO', 'LIBERADO', 'BLOQUEADO', 'DEPURADO')");
                        });
                });

            modelBuilder.Entity("Cadastro.Domain.Entities.HistoricoBloqueio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Justificativa")
                        .HasColumnType("VARCHAR(500)");

                    b.HasKey("Id");

                    b.HasIndex("EntidadeTipo", "EntidadeId")
                        .HasDatabaseName("ix_historico_entidade");

                    b.ToTable("historico_bloqueios", "cadastro", t =>
                        {
                            t.HasCheckConstraint("ck_historico_acao", "\"Acao\" IN ('BLOQUEIO', 'DESBLOQUEIO')");

                            t.HasCheckConstraint("ck_historico_tipo", "\"EntidadeTipo\" IN ('OBRA', 'FONOGRAMA')");
                        });
                });

            modelBuilder.Entity("Cadastro.Domain.Entities.ObraMusical", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BloqueioJustificativa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DominioPublico")
                        .HasColumnType("boolean");

                    b.Property<string>("Genero")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Iswc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ObraDepuradaParaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Subtitulo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Iswc")
                        .IsUnique()
                        .HasDatabaseName("uq_obras_iswc")
                        .HasFilter("\"Iswc\" IS NOT NULL");

                    b.HasIndex("ObraDepuradaParaId")
                        .HasDatabaseName("ix_obras_depurada_para")
                        .HasFilter("\"ObraDepuradaParaId\" IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_obras_status");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_obras_tipo");

                    b.ToTable("obras_musicais", "cadastro", t =>
                        {
                            t.HasCheckConstraint("ck_obras_status", "\"Status\" IN ('PENDENTE', 'LIBERADO', 'BLOQUEADO', 'DOMINIO_PUBLICO', 'DEPURADA')");
                        });
                });

            modelBuilder.Entity("Cadastro.Domain.Entities.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt", "Attempts")
                        .HasDatabaseName("ix_outbox_pendentes")
                        .HasFilter("\"PublishedAt\" IS NULL AND \"Attempts\" < 10");

                    b.ToTable("outbox_events", "cadastro");
                });

            modelBuilder.Entity("Cadastro.Domain.Entities.ParticipacaoConexa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("FonogramaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FonogramaId1")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Percentual")
                        .HasColumnType("DECIMAL(8,4)");

                    b.Property<Guid>("TitularId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FonogramaId")
                        .HasDatabaseName("ix_participacoes_fonograma");

                    b.HasIndex("FonogramaId1");

                    b.HasIndex("TitularId")
                        .HasDatabaseName("ix_participacoes_titular");

                    b.HasIndex("FonogramaId", "TitularId", "Categoria")
                        .IsUnique()
                        .HasDatabaseName("uq_participacoes_fono_titular_cat");

                    b.ToTable("participacoes_conexas", "cadastro", t =>
                        {
                            t.HasCheckConstraint("ck_participacoes_categoria", "\"Categoria\" IN ('INTERPRETE', 'PRODUTOR_FONOGRAFICO', 'MUSICO_EXECUTANTE')");

                            t.HasCheckConstraint("ck_participacoes_percentual", "\"Percentual\" IS NULL OR (\"Percentual\" > 0 AND \"Percentual\" <= 100)");
                        });
                });

            modelBuilder.Entity("Cadastro.Domain.Entities.Titular", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssociacaoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CaeIpi")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CaeIpi");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("Cnpj");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("Cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(2)");

                    b.HasKey("Id");

                    b.HasIndex("AssociacaoId")
                        .HasDatabaseName("ix_titulares_associacao");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("uq_titulares_cnpj")
                        .HasFilter("\"Cnpj\" IS NOT NULL");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("uq_titulares_cpf")
                        .HasFilter("\"Cpf\" IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_titulares_status");

                    b.ToTable("titulares", "cadastro");
                });

            modelBuilder.Entity("Cadastro.Domain.Entities.TitularidadeAutoral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ObraMusicalId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("DECIMAL(8,4)");

                    b.Property<Guid>("TitularId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ObraId")
                        .HasDatabaseName("ix_titularidades_obra");

                    b.HasIndex("ObraMusicalId");

                    b.HasIndex("TitularId")
                        .HasDatabaseName("ix_titularidades_titular");

                    b.HasIndex("ObraId", "TitularId", "Categoria")
                        .IsUnique()
                        .HasDatabaseName("uq_titularidades_obra_titular_categoria");

                    b.ToTable("titularidades_autorais", "cadastro", t =>
                        {
                            t.HasCheckConstraint("ck_titularidades_categoria", "\"Categoria\" IN ('AUTOR', 'EDITOR')");

                            t.HasCheckConstraint("ck_titularidades_percentual", "\"Percentual\" > 0 AND \"Percentual\" <= 100");
                        });
                });

            modelBuilder.Entity("Cadastro.Domain.Entities.Fonograma", b =>
                {
                    b.HasOne("Cadastro.Domain.Entities.Fonograma", "FonogramaDepuradoPara")
                        .WithMany()
                        .HasForeignKey("FonogramaDepuradoParaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cadastro.Domain.Entities.ObraMusical", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FonogramaDepuradoPara");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Cadastro.Domain.Entities.ObraMusical", b =>
                {
                    b.HasOne("Cadastro.Domain.Entities.ObraMusical", "ObraDepuradaPara")
                        .WithMany()
                        .HasForeignKey("ObraDepuradaParaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ObraDepuradaPara");
                });

            modelBuilder.Entity("Cadastro.Domain.Entities.ParticipacaoConexa", b =>
                {
                    b.HasOne("Cadastro.Domain.Entities.Fonograma", "Fonograma")
                        .WithMany()
                        .HasForeignKey("FonogramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cadastro.Domain.Entities.Fonograma", null)
                        .WithMany("ParticipacoesConexas")
                        .HasForeignKey("FonogramaId1");

                    b.HasOne("Cadastro.Domain.Entities.Titular", "Titular")
                        .WithMany()
                        .HasForeignKey("TitularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fonograma");

                    b.Navigation("Titular");
                });

            modelBuilder.Entity("Cadastro.Domain.Entities.Titular", b =>
                {
                    b.HasOne("Cadastro.Domain.Entities.Associacao", "Associacao")
                        .WithMany()
                        .HasForeignKey("AssociacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Associacao");
                });

            modelBuilder.Entity("Cadastro.Domain.Entities.TitularidadeAutoral", b =>
                {
                    b.HasOne("Cadastro.Domain.Entities.ObraMusical", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cadastro.Domain.Entities.ObraMusical", null)
                        .WithMany("TitularidadesAutorais")
                        .HasForeignKey("ObraMusicalId");

                    b.HasOne("Cadastro.Domain.Entities.Titular", "Titular")
                        .WithMany()
                        .HasForeignKey("TitularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("Titular");
                });

            modelBuilder.Entity("Cadastro.Domain.Entities.Fonograma", b =>
                {
                    b.Navigation("ParticipacoesConexas");
                });

            modelBuilder.Entity("Cadastro.Domain.Entities.ObraMusical", b =>
                {
                    b.Navigation("TitularidadesAutorais");
                });
#pragma warning restore 612, 618
        }
    }
}
