// <auto-generated />
using System;
using Cadastro.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cadastro.Infra.Data.Migrations
{
    [DbContext(typeof(CadastroDbContext))]
    partial class CadastroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cadastro")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cadastro.Domain.Entities.Associacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character(18)")
                        .IsFixedLength();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("uq_associacoes_cnpj");

                    b.HasIndex("Sigla")
                        .IsUnique()
                        .HasDatabaseName("uq_associacoes_sigla");

                    b.ToTable("associacoes", "cadastro");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Cnpj = "50.997.063/0001-32",
                            Nome = "Associação Brasileira de Música e Artes",
                            Sigla = "ABRAMUS"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            Cnpj = "30.713.325/0001-82",
                            Nome = "Associação de Músicos, Arranjadores e Regentes",
                            Sigla = "AMAR"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            Cnpj = "43.985.563/0001-99",
                            Nome = "Associação de Intérpretes e Músicos",
                            Sigla = "ASSIM"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            Cnpj = "33.780.222/0001-23",
                            Nome = "Sociedade Brasileira de Autores, Compositores e Escritores de Música",
                            Sigla = "SBACEM"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-efab-345678901234"),
                            Cnpj = "62.092.010/0001-51",
                            Nome = "Sociedade Independente de Compositores e Autores Musicais",
                            Sigla = "SICAM"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            Cnpj = "33.748.146/0001-79",
                            Nome = "Sociedade Brasileira de Administração e Proteção de Direitos Intelectuais",
                            Sigla = "SOCINPRO"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-3456-abcd-567890123456"),
                            Cnpj = "33.576.166/0001-00",
                            Nome = "União Brasileira de Compositores",
                            Sigla = "UBC"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
