server {
    listen       80;
    server_name  _;
    root         /usr/share/nginx/html;

    location = / {
        index index.html;
    }

    location /v1/ {
        autoindex on;
        autoindex_format json;
        default_type application/json;
        add_header Access-Control-Allow-Origin "*" always;
    }

    location ~* \.json$ {
        default_type application/json;
        add_header Cache-Control "public, max-age=3600";
        add_header Access-Control-Allow-Origin "*" always;
    }
}
