spring:
  config:
    activate:
      on-profile: dev

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: INFO
    br.org.ecad.authz.sdk: DEBUG

ecad:
  authz:
    enabled: ${AUTHZ_ENABLED:true}
    base-url: ${AUTHZ_BASE_URL:http://localhost:8085}
    catalog:
      registration-required: ${AUTHZ_CATALOG_REGISTRATION_REQUIRED:true}
      service-name: arrecadacao
